name: CI

on: [push, pull_request]

jobs:
  setup-environment:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install -r requirements.txt

  run-tests:
    needs: setup-environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Unit Tests
        run: |
          pytest tests/

  static-analysis:
    needs: setup-environment
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Run Linter
        run: |
          pip install flake8
          flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

  deploy-dashboard:
    needs: [setup-environment, run-tests, static-analysis]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Streamlit Cloud
        run: |
          streamlit run app/main.py
